-- Description: auto-created by ExcelToLua tool.
-- Author:jjc

module("res", package.seeall)


keys = {
	"﻿id", "img", 
}

resTable = {
    id_1 = {"Image/Fight/player/caoren/caoren.ExportJson", },
    id_2 = {"Image/Fight/player/diaochan/diaochan.ExportJson", },
    id_3 = {"Image/Fight/player/dunbing/dunbing.ExportJson", },
    id_4 = {"Image/Fight/player/ganning/ganning.ExportJson", },
    id_5 = {"Image/Fight/player/guanyu/guanyu.ExportJson", },
    id_6 = {"Image/Fight/player/huatuo/huatuo.ExportJson", },
    id_7 = {"Image/Fight/player/hufahuajing/hufahuajing.ExportJson", },
    id_8 = {"Image/Fight/player/hufa_long/hufa_long.ExportJson", },
    id_9 = {"Image/Fight/player/lvbu/lvbu.ExportJson", },
    id_10 = {"Image/Fight/player/machao/machao.ExportJson", },
    id_11 = {"Image/Fight/player/pushanbing/pushanbing.ExportJson", },
    id_12 = {"Image/Fight/player/qiangbing/qiangbing.ExportJson", },
    id_13 = {"Image/Fight/player/toushiche/toushiche.ExportJson", },
    id_14 = {"Image/Fight/player/yanlong/yanlong.ExportJson", },
    id_15 = {"Image/Fight/player/zhaoyun/zhaoyun.ExportJson", },
    id_16 = {"Image/Fight/skill/buff_huixue001/buff_huixue001.ExportJson", },
    id_17 = {"Image/Fight/skill/diaochan_attack/diaochan_attack.ExportJson", },
    id_18 = {"Image/Fight/skill/diaochan_hitted001/diaochan_hitted001.ExportJson", },
    id_19 = {"Image/Fight/skill/diaochan_hitted003_01/diaochan_hitted003_01.ExportJson", },
    id_20 = {"Image/Fight/skill/dunbing_manualskill/dunbing_manualskill.ExportJson", },
    id_21 = {"Image/Fight/skill/ganning_attack/ganning_attack.ExportJson", },
    id_22 = {"Image/Fight/skill/ganning_hitted/ganning_hitted.ExportJson", },
    id_23 = {"Image/Fight/skill/ganning_manualskill/ganning_manualskill.ExportJson", },
    id_24 = {"Image/Fight/skill/ganning_skill/ganning_skill.ExportJson", },
    id_25 = {"Image/Fight/skill/guanyu_hitted001/guanyu_hitted001.ExportJson", },
    id_26 = {"Image/Fight/skill/gushou_attack001/gushou_attack001.ExportJson", },
    id_27 = {"Image/Fight/skill/gushou_hitted001/gushou_hitted001.ExportJson", },
    id_28 = {"Image/Fight/skill/gushou_hitted03/gushou_hitted03.ExportJson", },
    id_29 = {"Image/Fight/skill/huatuo_skill01/huatuo_skill01.ExportJson", },
    id_30 = {"Image/Fight/skill/huatuo_skill01_02/huatuo_skill01_02.ExportJson", },
    id_31 = {"Image/Fight/skill/huatuo_skill02_01/huatuo_skill02_01.ExportJson", },
    id_32 = {"Image/Fight/skill/huatuo_skill02_02/huatuo_skill02_02.ExportJson", },
    id_33 = {"Image/Fight/skill/hufalong_hitted001/hufalong_hitted001.ExportJson", },
    id_34 = {"Image/Fight/skill/lvbu_hitted/lvbu_hitted.ExportJson", },
    id_35 = {"Image/Fight/skill/lvbu_manualskill01/lvbu_manualskill01.ExportJson", },
    id_36 = {"Image/Fight/skill/lvbu_manualskill02/lvbu_manualskill02.ExportJson", },
    id_37 = {"Image/Fight/skill/machao_buff001/machao_buff001.ExportJson", },
    id_38 = {"Image/Fight/skill/machao_hitted001/machao_hitted001.ExportJson", },
    id_39 = {"Image/Fight/skill/pushanbing_bullet001/pushanbing_bullet001.ExportJson", },
    id_40 = {"Image/Fight/skill/pushanbing_hitted001/pushanbing_hitted001.ExportJson", },
    id_41 = {"Image/Fight/skill/pushanbing_skill001/pushanbing_skill001.ExportJson", },
    id_42 = {"Image/Fight/skill/qiangbing_attack001/qiangbing_attack001.ExportJson", },
    id_43 = {"Image/Fight/skill/toushiche_attack001/toushiche_attack001.ExportJson", },
    id_44 = {"Image/Fight/skill/toushiche_hitted/toushiche_hitted.ExportJson", },
    id_45 = {"Image/Fight/skill/toushiche_hitted002/toushiche_hitted002.ExportJson", },
    id_46 = {"Image/Fight/skill/toushiche_hitted002_01/toushiche_hitted002_01.ExportJson", },
    id_47 = {"Image/Fight/skill/toushiche_skill001/toushiche_skill001.ExportJson", },
    id_48 = {"Image/Fight/skill/xuanzhong_guangquan001/xuanzhong_guangquan001.ExportJson", },
    id_49 = {"Image/Fight/skill/yanlong_attack001/yanlong_attack001.ExportJson", },
    id_50 = {"Image/Fight/skill/yanlong_hitted001_01/yanlong_hitted001_01.ExportJson", },
    id_51 = {"Image/Fight