
NET_MSG_TYPE_ID = {						
	TYPE_C_GS = 0,
	TYPE_GS_C = 1,
	TYPE_C_MS = 2,
	TYPE_MS_C = 3,
	TYPE_G_MS = 4,
	TYPE_MS_G = 5,	
	--国战
	TYPE_B_MS = 6,
	TYPE_MS_B = 7,
	TYPE_C_BS = 8,

	TYPE_MAXCOUNT = 9,
}

C_GS_NET_MSG_ID = {						
	C_GS_GETSRVLIST_NEW 		= 0,
	C_GS_LOGIN					= 1,
	C_GS_JOINMS					= 2,
	C_GS_CREATECHAR 			= 3,
	C_GS_FTPSERVER				= 4,
	C_GS_SDKLOGIN               = 5,
	C_GS_MAXCOUNT 				= 6,	
}

GS_C_NET_MSG_ID = {						
	GS_C_GETSRVLIST_NEW_RETURN	= 0,
	GS_C_LOGIN_RETURN			= 1,
	GS_C_JOINMS_RETURN			= 2,
	C_GS_CREATECHAR_RETURN		= 3,
	GS_C_FTPSERVER_RETURN		= 4,
	GS_C_MAXCOUNT				= 5,	
}


C_MS_NET_MSG_ID = {		
	C_MS_LOGIN					= 0,
	C_MS_GETGENERALLIST			= 1,
	C_MS_GETBASEDATA			= 2,
	C_MS_GETBAGITEMLIST			= 3,
	C_MS_GETEQUIPLIST			= 4,
	C_MS_GETMATRIX				= 5,
	C_MS_SHOPLIST				= 6,
	C_MS_USEITEM_BOX			= 7,
	C_MS_BUYITEM				= 8,
	C_MS_USEEQUIP				= 9,
	C_MS_CHANGEMATRIX			= 10,
	C_MS_HEART					= 11,
	C_MS_UPDATEITEMBAG			= 12,
	C_MS_UPDATEEQUIPBAG			= 13,
	C_MS_UPDATEGENERALBAG		= 14,
	C_MS_UPDATEMATRIX			= 15,
	C_MS_UPDATATBASEINFO		= 16,
	C_MS_USEITEM				= 17,
	C_MS_SELLITEM				= 18,
	C_MS_GETALL					= 19,
	C_MS_BATTLEBEGIN			= 20,
	C_MS_BATTLEEND				= 21,
	C_MS_STRENGTHENEQUIP		= 22,
	C_MS_UPDATATSHOP			= 23,
	C_MS_EQUIPXILIAN			= 24,
	C_MS_XILIANRESULT			= 25,
	C_MS_UPLVGENERAL			= 26,
	C_MS_STRENGTHENTREASURE		= 27,
	C_MS_XILIANTREASURE			= 28,
	C_MS_REFRSHSHOP				= 29,
	C_MS_TIAMING				= 30,
	C_MS_DANYAO					= 31,
	C_MS_RANDNAME				= 32,
	C_MS_CREATECHARACTER		= 33,
	C_MS_ZHUANJING_LVUP			= 34,
	C_MS_MAINSTAY_CHANGEJOP		= 35,
	C_MS_MAINSTAY_JIHUO			= 36,
	C_MS_GETZHUANJIANG			= 37,
	C_MS_UPRAIDJOP				= 38,
	C_MS_POST_PACKET_GETALL 	= 39,
	C_MS_FRONTBATTLE			= 40,
	C_MS_FUBENBTNINFO			= 41,
	C_MS_PVPINFO				= 42,
	C_MS_LBSTRENGTHEN           = 43,
	C_MS_REFINING_EQUIP         = 44,	
	C_MS_MAIL_GET_FULL			= 45,
	C_MS_MAIL_GET_ONE			= 46,
	C_MS_MAIL_DELETE			= 47,
	C_MS_MAIL_DRAW				= 48,
	C_MS_CHAT 					= 49,
	C_MS_PLAYER_BRIEF			= 50,
	C_MS_RANKING_LIST           = 51,
	C_MS_TOURNAMENT_LIST        = 52,--比武数据
	C_MS_LUCKYDRAM 				= 53,
	C_MS_PLAY_BACK              = 54,--比武记录
	C_MS_GET_PLAY_BACK          = 55,--具体的对战记录
	C_MS_CHANGE_MODELS_3D       = 56,--保存3D模型
	C_MS_BATTLEMOPUP 			= 57,
	C_MS_CLIMBINGTOWERSET 		= 58,
	C_MS_OPEN_SNATCH            = 59,--打开抢夺的列表
	C_MS_SNATCH                 = 60,-- 夺宝战斗的结果
	C_MS_SNATCH_ENEMY           = 61,--夺宝的敌人
	C_MS_SNATCH_OPEN_BOX        = 62,--打开夺宝界面的宝箱
	C_MS_CORPS_CREATE           = 63,--创建军团
	C_MS_CORPS_DELETE           = 64,--解散军团
	C_MS_CORPS_FIND             = 65,--查找军团列表
	C_MS_CORPS_FIND_ONE         = 66,--查找单个军团
	C_MS_CORPS_APPLY            = 67,--申请加入军团
	C_MS_CORPS_GET_LIST         = 68,--获取申请/邀请列表
	C_MS_CORPS_APPLY_OPERATOR   = 69,--操作军团申请列表
	C_MS_CORPS_APPLY_CANNCEL    = 70,--撤销军团申请
	C_MS_CORPS_GET_INFO         = 71,--获取本军团信息
	C_MS_CORPS_GET_MEMBER_LIST  = 72,--查看成员列表
	C_MS_CORPS_LEAVE            = 73,--成员离开军团
	C_MS_CORPS_SETTINGS         = 74,--军团设置
	C_MS_CORPS_DYNAMIC          = 75,--军团动态
	C_MS_CORPS_APPOINT          = 76,--修改军团官职
	C_MS_CORPS_EXPEL            = 77,--军团开除成员
	C_MS_CORPS_SCIENCE_UP       = 78,--军团科技升级
	C_MS_TOURNAMENT_LIST_MATRIX = 79,--获取每个排名的阵容信息
	C_MS_CORPS_SCIENCE_UPDATE   = 80,
	C_MS_CORPS_SCIENCE_ASSET_INJECTION  = 81,--军团注资
	C_MS_CORPS_SCIENCE_MESS_GET = 82,--军团食堂领取
	C_MS_CORPS_SCIENCE_LEVELE   = 83,--获取全部军团科技等级
	C_MS_CORPS_SCIENCE_DONATE_GET = 84,--军团捐献
	C_MS_BS_LOAD_FINISH  		= 85, --准备国战界面loading完成
	C_MS_CORPS_GET_MEMBER_INFO  = 86,
	C_MS_CORPS_GET_RECOMMEND_COUNTRY = 87,--获取军团推荐国家
	C_MS_MERCENARY_RESERVE      = 88,--获取所有佣兵机器人的基本信息
	C_MS_MERCENARY_SERVICE      = 89,--获取已拥有佣兵的基本信息
	C_MS_MERCENARY_REFRESH_RESERVE = 90,--获取佣兵待选列表
	C_MS_MERCENARY_HIRE         =91,--雇佣佣兵
	C_MS_MERCENARY_FIRE         = 92,--解雇佣兵
	C_MS_MERCENARY_RENEW        = 93,--佣兵续费
	C_MS_GET_MERCENARY_INFO     = 94,--获取佣兵阵容信息
	C_MS_CORPS_TREE_GET         = 95,--神树领取
	C_MS_CHANGE_NICKNAME        = 96,--玩家修改昵称 celina
	C_MS_SIGN_IN_GET_TAB        = 97,--获取签到奖励信息
	C_MS_SIGN_IN_GET_REWARD     = 98,--领取签到奖励
	C_MS_SIGN_IN_GET_ADVANCED   = 99,--领取豪华签到奖励
	C_MS_SCIENCE_SPEED_UP       = 100,--科技研发加速
	C_MS_RECHARGE               = 101,--充值协议
	C_MS_BUY_COUNT              = 102,--VIP购买次数
	C_MS_GET_VIP_REWARD         = 103,--VIP奖励领取
	C_MS_VIP_REWARD_STATUS      = 104,--VIP奖励领取状态
	C_MS_ACTIVATE_JALL_GRID     = 105,--开启牢房格子
	C_MS_JALL_GRID_INFO         = 106,--获取牢房格子信息
	C_MS_JALL_GET_BOX           = 107,--领取牢房奖励箱子
	C_MS_JALL_BOX_INFO          = 108,--获取牢房奖励箱子信息
	C_MS_JALL_USE_ITEM          = 109,--使用牢房加成道具
	C_MS_JALL_ITEM_INFO         = 110,--获取牢房加成道具信息
	C_MS_JALL_DELIVERABLES      = 111,--交付牢房任务 
	C_MS_TREASON                = 112,--叛国的协议
	C_MS_GET_COUNTRY_POWER      = 113,--获得三个国家的战力 celina
	C_MS_ANIMAL_GET_PRESTIGE    = 114,--获取灵兽声望信息
	C_MS_ANIMAL_GET_INFO        = 115,--获取灵兽具体信息
	C_MS_ANIMAL_BLESS           = 116,--选择赐福战队
	C_MS_ANIMAL_TRIBUTE         = 117,--进贡
	C_MS_ANIMAL_BAHAMUT         = 118,--召唤巴哈姆特
	C_MS_CATCH_LIST             = 119,--牢房抓捕
	C_MS_MERCENARY_ANIMAL       = 120,--获取佣兵灵兽加成信息
	C_MS_GET_ATTR_TIME          = 121,--获取更新体力和耐力的时间
	C_MS_GET_BAHAMUT_ROBOT      = 122,--获取巴哈巴哈姆特机器人
	C_MS_STRENGTHENEQUIP_AUTO   = 123,--一键强化
	C_MS_TREE_SPEED_UP          = 124,--神树果实加速
	C_MS_CLIMBING_GAIN 			= 125,--爬塔购买增益
	C_MS_BS_MOVE 				= 200,--国战队伍移动
	C_MS_BS_QUERY_WARCITY_CORPSLIST = 201,--点击城市的交战状态的攻守方信息
	C_MS_BS_LOOK_CITY           = 202,--国战的攻城战界面信息
	C_MS_BS_CITYPVPINFO         = 203,--国战的攻城战详细战斗请求
	C_MS_BS_LOOK_CITY_CORPSLIST = 204,--攻城战里面查看队伍列表信息 celina
	C_MS_BS_QUERY_CORPS_OPERATE = 205,--查询可以撤退或者突进的队列
	C_MS_BS_SINGLE_BATTLE       = 206,--通知单挑
	C_MS_BS_CORPSPVPINFO        = 207,--去请求单挑的战斗数据
	C_MS_BS_PLAYER_BLOOD 		= 208,--停止血战或坚守
	C_MS_BS_CLONE_CORPS         = 209,--通知分身
	C_MS_BS_QUERY_COUNTRY_INFO  = 210,--国家信息
	C_MS_BS_COUNTRY_LEVELUP     = 211,--国家升级
	C_MS_BS_GAIN_REWARD         = 212,--领取国战奖励
	C_MS_BS_CLICK_FOG_CITY 		= 213,--请求迷雾城市信息
	C_MS_BS_CORPS_START_FOG_WAR = 214,--请求迷雾战
	C_MS_BS_RELEASE_PRISON 		= 215,--请求离开牢狱
	C_MS_BS_QUERY_MC_INFO       = 216,--客户端查询神兽远征军信息
	C_MS_BS_USE_ITEM 			= 217,--使用国战物品
	C_MS_GET_DALIY_TASK_INFO 	= 401,--任务信息
	C_MS_GET_DALIY_TASK_REWARD_INFO = 402,--任务奖励
	C_MS_GET_DALIY_TASK_TREASURE_REWARD = 403,--领取日常箱子奖励
	C_MS_GET_WAR_TASK_INFO 		= 404,--请求国战任务数据
	C_MS_CORPS_TASK_REFRESH 	= 405,--请求军团任务数据刷新
	C_MS_SET_NEWBIE_GUIDE_FLAG  = 406,--请求新手引导的数据
	C_MS_BULK_SALE              = 407,--请求批量出售装备
	C_MS_REQUEST_DATA           = 408,--告诉服务器可以更新数据了
	C_MS_MAXCOUNT				= 152,
}

MS_C_NET_MSG_ID = {		
	MS_C_LOGIN_RETURN			= 0,
	MS_C_GETGENERALLIST_RETURN	= 1,
	MS_C_GETBASEDATA_RETURN		= 2,
	MS_C_GETBAGITEMLIST_RETURN	= 3,
	MS_C_GETEQUIPLIST_RETURN	= 4,
	MS_C_GETMATRIX_RETURN		= 5,
	MS_C_SHOPLIST_RETURN		= 6,
	MS_C_USEITEM_BOX_RETURN		= 7,
	MS_C_BUYITEM_RETURN			= 8,
	MS_C_USEEQUIP_RETURN		= 9,
	MS_C_CHANGEMATRIX_RETURN	= 10,
	MS_C_HEART_RETURN	   		= 11,
	MS_C_UPDATEITEMBAG_RETURN	= 12,
	MS_C_UPDATEEQUIPBAG_RETURN	= 13,
	MS_C_UPDATEGENERALBAG_RETURN = 14,
	MS_C_UPDATEMATRIX_RETURN	= 15,
	MS_C_UPDATATBASEINFO_RETURN	= 16,
	MS_C_USEITEM_RETURN			= 17,
	MS_C_SELLITEM_RETURN		= 18,
	MS_C_GETALL_RETURN			= 19,
	MS_C_BATTLEBEGIN_RETURN		= 20,
	MS_C_BATTLEEND_RETURN		= 21,
	MS_C_STRENGTHENEQUIP_RETURN	= 22,
	MS_C_UPDATATSHOP_RETURN		= 23,
	MS_C_EQUIPXILIAN_RETURN		= 24,
	MS_C_XILIANRESULT_RETURN 	= 25,
	MS_C_UPLVGENERAL_RETURN		= 26,
	MS_C_STRENGTHENTREASURE_RETURN = 27,
	MS_C_XILIANTREASURE_RETURN	= 28,
	MS_C_REFRSHSHOP_RETURN		= 29,
	MS_C_TIAMING_RETURN			= 30,
	MS_C_DANYAO_RETURN  		= 31,
	MS_C_RANDNAME_RETURN		= 32,
	MS_C_CREATECHARACTER_RETURN = 33,
	MS_C_ZHUANJING_LVUP_RETURN	= 34,
	MS_C_MAINSTAY_CHANGEJOP_RETURN = 35,
	MS_C_MAINSTAY_JIHUO_RETURN	= 36,
	MS_C_GETZHUANJIANG_RETURN	= 37,
	MS_C_UPRAIDJOP_RETURN		= 38,
	MS_C_POST_PACKET_GETALL_RETURN 	= 39,
	MS_C_FRONTBATTLE_RETURN			= 40,
	MS_C_FUBENBTNINFO_RETURN		= 41,
	MS_C_PVPINFO_RETURN				= 42,
	MS_C_LBSTRENGTHEN_RETURN        = 43,
	MS_C_REFINING_EQUIP_RETURN      = 44,	
	MS_C_MAIL_NEW				= 45,	
	MS_C_MAIL_GET_ONE			= 46,
	MS_C_MAIL_DELETE			= 47,
	MS_C_MAIL_GET_FULL			= 48,
	MS_C_CHAT 					= 49,
	MS_C_PLAYER_BRIEF			= 50,
	MS_C_RANKING_LIST           = 51,
	MS_C_TOURNAMENT_LIST        = 52,
	MS_C_LUCKYDRAM_RETURN 		= 53,
	MS_C_PLAY_BACK              = 54,--比武记录
	MS_C_GET_PLAY_BACK          = 55,
	MS_C_CHANGE_MODELS_3D       = 56,
	C_MS_BATTLEMOPUP_RETURN 	= 57,
	MS_C_CLIMBINGTOWERSET_RETURN  = 58,
	MS_C_OPEN_SNATCH            = 59,
	MS_C_SNATCH                 = 60,
	MS_C_SNATCH_ENEMY           = 61,
	MS_C_SNATCH_OPEN_BOX        = 62,
	MS_C_CORPS_CREATE           = 63,--创建军团
    MS_C_CORPS_DELETE           = 64,
    MS_C_CORPS_FIND             = 65,
    MS_C_CORPS_FIND_ONE         = 66,
    MS_C_CORPS_APPLY            = 67,
    MS_C_CORPS_GET_LIST         = 68,
    MS_C_CORPS_APPLY_OPERATOR   = 69,
    MS_C_CORPS_APPLY_CANNCEL    = 70,
    MS_C_CORPS_GET_INFO         = 71,
    MS_C_CORPS_GET_MEMBER_LIST  = 72,
    MS_C_CORPS_LEAVE            = 73,
    MS_C_CORPS_SETTINGS         = 74,
    MS_C_CORPS_DYNAMIC          = 75,
    MS_C_CORPS_APPOINT          = 76,
    MS_C_CORPS_EXPEL            = 77,
    MS_C_CORPS_SCIENCE_UP       = 78,
    MS_C_TOURNAMENT_LIST_MATRIX = 79,
    MS_C_CORPS_SCIENCE_LEVEL_UP = 80,--返回一个科技升级成功及当前等级
    MS_C_CORPS_SCIENCE_UPDATE   = 81,
    MS_C_CORPS_SCIENCE_ASSET_INJECTION  = 82,
    MS_C_CORPS_SCIENCE_MESS_GET = 83,
    MS_C_CORPS_SCIENCE_LEVELE   = 84,
    MS_C_CORPS_SCIENCE_DONATE_GET = 85,
    MS_C_CORPS_GET_MEMBER_INFO  = 86,
    MS_C_CORPS_GET_RECOMMEND_COUNTRY = 87,
    MS_C_MERCENARY_RESERVE      = 88,
    MS_C_MERCENARY_SERVICE      = 89,
    MS_C_MERCENARY_REFRESH_RESERVE = 90,
    MS_C_MERCENARY_HIRE          = 91,
    MS_C_MERCENARY_FIRE         = 92,
    MS_C_MERCENARY_RENEW        = 93,
    MS_C_GET_MERCENARY_INFO     = 94,
    MS_C_CORPS_TREE_GET         = 95,
	MS_C_CHANGE_NICKNAME        = 96,--玩家修改昵称
    MS_C_SIGN_IN_GET_TAB        = 97,
    MS_C_SIGN_IN_GET_REWARD     = 98,
    MS_C_SIGN_IN_GET_ADVANCED   = 99,
    MS_C_MERCENARY_STATE 		= 100,
    MS_C_SCIENCE_SPEED_UP       = 101,
    MS_C_SHOP_OPEN              = 102,--商店打开关闭通知
	MS_C_FORCE_OFFLINE          = 103,--账号在异地登陆的推送 celina
	MS_C_RECHARGE               = 104,
	MS_C_SYSTEM_NOTICE          = 105,
	MS_C_BUY_COUNT              = 106,
	MS_C_GET_VIP_REWARD         = 107,
	MS_C_VIP_REWARD_STATUS      = 108,
	MS_C_ACTIVATE_JALL_GRID     = 109,
	MS_C_JALL_GRID_INFO         = 110,
	MS_C_JALL_GET_BOX           = 111,
	MS_C_JALL_BOX_INFO          = 112,
	MS_C_JALL_USE_ITEM          = 113,
	MS_C_JALL_ITEM_INFO         = 114,
	MS_C_JALL_DELIVERABLES      = 115,
	MS_C_TREASON                = 116, --叛国的协议回复
	MS_C_GET_COUNTRY_POWER      = 117,--获得三个国家的战力 celina
	MS_C_UPDATE_BASE            = 118,--更新基本数据 celina
	MS_C_ANIMAL_GET_PRESTIGE    = 119,
	MS_C_ANIMAL_GET_INFO        = 120,
	MS_C_ANIMAL_BLESS           = 121,
	MS_C_ANIMAL_TRIBUTE         = 122,
	MS_C_ANIMAL_BAHAMUT         = 123,
	MS_C_CATCH_LIST             = 124,
	MS_C_MERCENARY_ANIMAL       = 125,
	MS_C_GET_ATTR_TIME          = 126, --获取更新时间
	MS_C_CUSTOM_NOTICE          = 127,
	MS_C_GET_BAHAMUT_ROBOT      = 128, --获取巴哈姆特机器人信息
	MS_C_LOGIN_BS_UP			= 129,
	MS_C_STRENGTHENEQUIP_AUTO   = 130,--一键强化--131
	MS_C_TREE_SPEED_UP          = 132,
	MS_C_UPDATE_ATTR            = 133,--发送玩家属性改变的消息
	MS_C_CLIMBING_GAIN 			= 134,--爬塔增益返回
    MS_C_BS_ALL_CITY_STATE 		= 200,
    MS_C_BS_TEAM_MESS 			= 201, 
    MS_C_BS_MOVE_RESULT  		= 202,
	MS_C_BS_WARCITY_CORPSLIST   = 203,--点击城市的交战状态的攻守方信息回复
    MS_C_BS_CITY_STATE 			= 204,
    MS_C_BS_COPRS_STOP  		= 205,
	MS_C_BS_LOOK_RESULT         = 206,--城市观战
	MS_C_BS_CITYPVPINFO_RETURN  = 207,--攻城战的详细战斗数据返回
	MS_C_BS_LOOK_CITY_CORPSLIST_RETURN = 208,--返回攻守列表的信息 celina
	MS_C_BS_QUERY_CORPS_OPERATE_RETURN  = 209,--返回可以撤退或者突进的队列
	MS_C_BS_SINGLE_BATTLE_RETURN = 210,--去单挑
	MS_C_BS_CORPSPVPINFO_RETURN  = 211,--得到单挑信息
	MS_C_BS_CORPS_STATE_RETURN   = 212, --改变队伍当前状态
	MS_C_BS_CORPS_BLOOD_RETURN   = 213,
	MS_C_BS_CLONE_CORPS_RETURN   = 214,--得到分身是否成功
	MS_C_BS_PLAYER_BLOOD_RETURN  = 215,
	MS_C_BS_PLAYER_DATA_RETURN   = 216,--国战中要得到的玩家信息
	MS_C_BS_QUERY_COUNTRY_INFO_RETURN = 217, --国家信息
	MS_C_BS_COUNTRY_LEVELUP_RETURN = 218,--国家升级
	MS_C_BS_BATTLE_RESULT        = 219,--攻城战的战斗结果
	MS_C_BS_UPDATE_CORPS_DATA	 = 220,--某个佣兵信息的创建或个更新
	MS_C_BS_CREATE_MERCENARY_DATA= 221,--删除某个佣兵信息
	MS_C_BS_CORPS_PARAM_UPDATE   = 222,--更新某个佣兵的某个属性
	MS_C_BS_EXPEDITION_DATA 	 = 223,--国战远征军的数据
	MS_C_BS_EXPEDITION_DELETE    = 224,--国战远征军数据的删除
	MS_C_BS_EXPEDITION_MOVE      = 225,--国战远征军移动
	MS_C_BS_SEND_REWARD          = 226,--MS推送给客户端国战奖励
	MS_C_BS_REWARD_RETURN        = 227,
	MS_C_ALL_FOG_DATA 			 = 228,--迷雾城市状态
	MS_C_CLICK_FOG_CITY_RETURN   = 229,--获得某个迷雾城市信息
	MS_C_CORPS_START_FOG_WAR_RETURN = 230,--请求迷雾战结果返回
	MS_C_FOG_STATUS_CHAGE 		 = 231,--迷雾城市状态改变
	MS_C_LOOK_CITY_CORPS_NUM     = 232, --观战攻守方的战队数量
	MS_C_IN_FOG_CORPS_INDEX      = 233,--迷雾观战返回玩家所在的战队数据
	MS_C_BS_RELEASE_PRISON_RESULT= 234,--解除牢房
	MS_C_BS_QUERY_MC_INFO_RESULT = 235,--神兽远征军信息
	MS_C_BS_WAR_COUNTRY_STATE	 = 236,--三国格局
	MS_C_BS_CORPS_MYTHICAL_CREATURES_INFO = 237,--国战内神兽BUFF信息
	MS_C_BS_USE_ITEM_RESULT      = 238, --使用国战物品结果
	MS_C_BS_PVP_REWARD_INFO      = 239,--单挑的结果信息
	MS_C_NOTIFY_TASK_RED_POINT 	 = 400, --有未领取的任务
	MS_C_GET_DALIY_TASK_INFO 	 = 401,--任务信息
	MS_C_GET_DALIY_TASK_REWARD_INFO = 402,--任务奖励
	MS_C_GET_DALIY_TASK_TREASURE_REWARD = 403,--领取日常箱子奖励
	MS_C_NOTIFY_TASK_UPDATE		 = 404,--任务更新
	MS_C_NOTIFY_TASK_RELEASE     = 405,--国战任务发布通知
	MS_C_GET_WAR_TASK_INFO 		 = 406,--国战任务数据返回
	MS_C_SEND_WAR_COUNTRY_TASK_DATA = 407,--更新国战组任务
	MS_C_CORPS_TASK_REFRESH 	 = 408,
	MS_C_SEND_CORPS_TASK_DATA    = 409,
	MS_C_UPDATE_FUBEN_BUY_COUNT  = 410,
	MS_C_DALIY_TREASURE_STATE_CHANGE = 411,
	MS_C_BULK_SALE_RESULT        = 412,
	MS_C_CURRENT_NEWBIE_GUIDE_FLAG  = 413,--服务器通知新手引导
	MS_C_SET_NEWBIE_GUIDE_FLAG_RESULT  = 414,--通知客户端标识为1或者-1 的字段结果
	MS_C_MAXCOUNT_RETURN		 = 189,
}

GS_MS_NET_MSG_ID = {						
	GS_MS_MAXCOUNT = 0,
	
}

MS_GS_NET_MSG_ID = {						
	MS_GS_MAXCOUNT = 0,
	
}
